In [1]:

#Study of Numpy and its Function

In [2]:
import numpy as np

In [3]:
emp_salary=np.random.randint(8,70,10)

In [4]:
emp_salary

array([34, 24, 27, 67, 33, 63, 27, 69, 32, 27])

In [5]:
#set minimum and maximum salary using a_min and a_max

In [6]:
np.clip(emp_salary,a_min=20,a_max=50)# if we use clip method then all maximum and minimum value we can set as per our use

array([34, 24, 27, 50, 33, 50, 27, 50, 32, 27])

In [7]:
#If you want to find actual salary which are less then or greater than some salary use np.where
#np.where gives index detail

In [8]:
print(np.where(emp_salary <25))

(array([1]),)


In [9]:
#If you want to see actual data, use index

In [10]:
emp_salary[[1,4]]

array([24, 33])

In [11]:
#similarly you can  check for any condition (<,>,=,==,<=,>=)

In [12]:
#Reshaping Otherways

In [13]:
import numpy as np
from numpy.random import randint as ri

In [14]:
a=ri(1,99,30)
print(a)

[20 60 70 90 20 50 74 30  1 98  9 49 95 60 60 92 16 19 11 85 15 69 28 65
 39  6 56 88 46 89]


In [15]:
b=a.reshape(2,3,5)
print(b)

[[[20 60 70 90 20]
  [50 74 30  1 98]
  [ 9 49 95 60 60]]

 [[92 16 19 11 85]
  [15 69 28 65 39]
  [ 6 56 88 46 89]]]


In [16]:
c=a.reshape(6,5)
print(c)

[[20 60 70 90 20]
 [50 74 30  1 98]
 [ 9 49 95 60 60]
 [92 16 19 11 85]
 [15 69 28 65 39]
 [ 6 56 88 46 89]]


In [17]:
print("Minimum of a is ",c.min())
print("Maximum of a is ",c.max())

Minimum of a is  1
Maximum of a is  98


In [18]:
#Sorting

In [19]:
m=ri(1,100,25).reshape(5,5) #matrix of random integer
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m))#default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m,axis=0))


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[99 52 88  4 66]
 [91  5 13 37 32]
 [25 40  6 38 67]
 [73 81 93  3 99]
 [50  3 18 62 74]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[ 4 52 66 88 99]
 [ 5 13 32 37 91]
 [ 6 25 38 40 67]
 [ 3 73 81 93 99]
 [ 3 18 50 62 74]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[25  3  6  3 32]
 [50  5 13  4 66]
 [73 40 18 37 67]
 [91 52 88 38 74]
 [99 81 93 62 99]]


In [20]:
# Index and slicing

In [21]:
arr=np.arange(13,30)
print("Array",arr)

Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [22]:
print("Element of 7th index is =",arr[7])

Element of 7th index is = 20


In [23]:
print("Element of 3rd and 5th index is = ",arr[3:5])

Element of 3rd and 5th index is =  [16 17]


In [24]:
print("Element up to 4th index are :",arr[4:])

Element up to 4th index are : [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [25]:
#Store arr in abc and check upto 4th index of abc

In [26]:
abc=arr[4:]
print(abc)

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [27]:
print("Element from last backwords : ",abc[-1::-2])

Element from last backwords :  [29 27 25 23 21 19 17]


In [28]:
print("7th elemets from last backword are : ",arr[-1:-8:-1])

7th elemets from last backword are :  [29 28 27 26 25 24 23]


In [29]:
print("Elements at 2nd 4th and 9th index are : ",arr[[2,4,9]])#Pass a list as a index to subset

Elements at 2nd 4th and 9th index are :  [15 17 22]


In [30]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print("Entire row at index 2: ",mat[2])

Entire row at index 2:  [7 8 9]


In [32]:
print("Entire column at index  3:\n",mat[:,1:])

Entire column at index  3:
 [[2 3]
 [5 6]
 [8 9]]


In [33]:
print("\nSubsetting Sub-Matricss\n---------")
print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",mat[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [34]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
print(mat[0:2,[1,2]])

[[2 3]
 [5 6]]


In [36]:
#Update Matrix

In [37]:
print("Original Matrix \n\n",mat)

Original Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
mat[0,2]=200

In [39]:
mat

array([[  1,   2, 200],
       [  4,   5,   6],
       [  7,   8,   9]])

In [40]:
mat[1,0]=100

In [41]:
mat

array([[  1,   2, 200],
       [100,   5,   6],
       [  7,   8,   9]])

In [42]:
#Subsetting-So what is subsetting ? subsetting means when we wann to fetch only few dara from matrix then we use subsetting method.

In [43]:
mat=np.array(ri(10,100,15)).reshape(3,5)
print('Matrix of random 2 digit number \n------\n',mat)

Matrix of random 2 digit number 
------
 [[15 32 37 33 92]
 [71 98 21 97 81]
 [81 22 22 29 44]]


In [44]:
print("Elements greater than 50\n ",mat[mat>50])

Elements greater than 50
  [92 71 98 97 81 81]


In [45]:
print(np.where(mat==98))

(array([1]), array([1]))


In [46]:
#You can also use np.where to return some data based on condtion

In [47]:
age=50
np.where(age>68,'Retired','Still Working')

array('Still Working', dtype='<U13')

In [48]:
#Universal Functions

In [49]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrics of Single digit number \n---------------\n",mat1)
print("\n 2st Matrics of Single digit number \n---------------\n",mat2)


 1st Matrics of Single digit number 
---------------
 [[3 1 1]
 [6 2 3]
 [4 4 5]]

 2st Matrics of Single digit number 
---------------
 [[9 6 6]
 [1 8 4]
 [1 3 3]]


In [50]:
print('mat1=\n',mat1)
print('mat2=\n',mat2)

mat1=
 [[3 1 1]
 [6 2 3]
 [4 4 5]]
mat2=
 [[9 6 6]
 [1 8 4]
 [1 3 3]]


In [51]:
print("\n Division \n---------------------\n",mat1/mat2)


 Division 
---------------------
 [[0.33333333 0.16666667 0.16666667]
 [6.         0.25       0.75      ]
 [4.         1.33333333 1.66666667]]


In [52]:
print("\n Linear combination : 3*A - 2*B \n",3*mat1-2*mat2)


 Linear combination : 3*A - 2*B 
 [[ -9  -9  -9]
 [ 16 -10   1]
 [ 10   6   9]]


In [53]:
#Broadcasting-
#Numpy operations are usually dont on pairs of arrays on an element by element basis. in the simplest case, the two arays must have exactly the same shape
# Numpy broadcasting rules relaxex this constraints when the array shape meet certain constraints when operatings on two array,
# Numpy compares their shape element wise it starts with the trailing dimensions ,and word its way forword ,two dimension are compatible
#when they are eqaul,or one of them is 1

In [54]:
start=np.zeros((3,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
#create a rank1 ndarray with 3 values

In [56]:
add_rows=np.array([[1,0,2]])
print(add_rows)

[[1 0 2]]


In [57]:
y=start+add_rows # add to each row of 'start' using broadcasting

In [58]:
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [59]:
new_row=add_rows.T # T is use for transpose it convert column into row #vice versa

In [60]:
new_row

array([[1],
       [0],
       [2]])

In [61]:
test=new_row+start
print(test)

[[1. 1. 1.]
 [0. 0. 0.]
 [2. 2. 2.]]


In [62]:
#craete table ndarray which is 4 X 1 to broadcast across coloumn

In [63]:
ad_cols=np.array([[0,2,2,3]])

In [64]:
ad_cols=ad_cols.T

In [65]:
ad_cols

array([[0],
       [2],
       [2],
       [3]])

In [66]:
#Array Math

In [67]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrix of random single digit number\n---------------------------\n",mat1)
print("\n 2nd Matrix of random single digit number\n---------------------------\n",mat2)

print("\n sq-root of 1st Matrix using np\n",'-'*50,"\n",np.sqrt(mat1))
print("\n square of 2nd Matrix using np\n",'-'*50,"\n",np.square(mat2))


 1st Matrix of random single digit number
---------------------------
 [[4 7 9]
 [4 7 5]
 [8 6 4]]

 2nd Matrix of random single digit number
---------------------------
 [[1 3 5]
 [5 1 1]
 [4 7 9]]

 sq-root of 1st Matrix using np
 -------------------------------------------------- 
 [[2.         2.64575131 3.        ]
 [2.         2.64575131 2.23606798]
 [2.82842712 2.44948974 2.        ]]

 square of 2nd Matrix using np
 -------------------------------------------------- 
 [[ 1  9 25]
 [25  1  1]
 [16 49 81]]


In [68]:
#Similarly you can apply other function to matrix to matrix
#please explore more function and practice