In [1]:

# Today we are learning about Numpy
# So, what is numpy ? Numpy means Numerical Python
# we have to import numpy as sqlite3.

In [2]:
import numpy as np

In [3]:
#check all the function of  numpy.

In [4]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [5]:
# This all are the numpy fucntion but as a datascientis we have to use few.

In [6]:
np.sqrt(10) # sqrt=square root

3.1622776601683795

In [7]:
print("Minimun ",np.amin([25,30,57,18]))

Minimun  18


In [8]:
print("Maximum ",np.amax([25,30,57,18]))

Maximum  57


In [9]:
#Rounded off to next number  using ceiling.

In [10]:
np.ceil(29.1) #its means when we use ceil they give roundfigured answer.

30.0

In [11]:
np.ceil(np.sqrt(10)) # both work together

4.0

In [12]:
np.ceil(np.sum(np.sqrt([5,10,15]))) #here we are first ceiling.then sum,then use square root.

10.0

In [13]:
# Similarly there are many numpy function ,you can explore them for you knowledge purpose .
# But we use limited function in our course let's explore them.

In [14]:
np.array([5,9,13])

array([ 5,  9, 13])

In [15]:
type([5,9,13])

list

In [16]:
xyz=np.array([5,9,13])

In [17]:
type(xyz)

numpy.ndarray

In [18]:
#Two Dimension

In [19]:
a=np.array([[1,2],[3,4],[4,5]])
print("Type - ",a.dtype)

print("\n",a)

Type -  int64

 [[1 2]
 [3 4]
 [4 5]]


In [20]:
#  dtype.conversion

In [21]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [22]:
#Covert a list into an array :

In [23]:
a=[1,2]
c=np.array(a)
print(c)

[1 2]


In [24]:
type(c)

numpy.ndarray

In [25]:
#copy array into other

In [26]:
b=np.asarray(c)
print(b)

[1 2]


In [27]:
# Data Types

In [28]:
import numpy as np

In [29]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print("Type/class of this object : ",type(mat))
print("Here is the marks \n------\n",mat,"\n-----------")
print("print dimension of this matrix : ",mat.ndim)#ndim gives dimension,2 for a matrix and 1 for vector
print("size of the matrix : ",mat.size)#size shows total number elements
print("Shape of the matrix : ",mat.shape)#shape shows how many rows and column
print("Data Type of the matrix ; ",mat.dtype)#shoes which type

Type/class of this object :  <class 'numpy.ndarray'>
Here is the marks 
------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
print dimension of this matrix :  2
size of the matrix :  9
Shape of the matrix :  (3, 3)
Data Type of the matrix ;  int64


In [30]:
#arange and linespace

In [31]:
#dont work with python range function

In [32]:
a=np.arange(10)

In [33]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#in numpy range function also work with float number

In [35]:
a=np.arange(10.5,20.4,2)

In [36]:
a

array([10.5, 12.5, 14.5, 16.5, 18.5])

In [37]:
#Reverse Order

In [38]:
print("Every 5th number from 50 in reverse order \n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order 
 [50 45 40 35 30 25 20 15 10  5  0]


In [39]:
print("linearly space numbers between 1 and 5 \n-------------")
print(np.linspace(10,40,5))

linearly space numbers between 1 and 5 
-------------
[10.  17.5 25.  32.5 40. ]


In [40]:
#Include end points and check space between the points
#By default endpoint=True
#Bydefaul retstep=False

In [41]:
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [42]:
print(np.linspace(4.5678,25.9865,39,retstep=True))

(array([ 4.5678 ,  5.13145,  5.6951 ,  6.25875,  6.8224 ,  7.38605,
        7.9497 ,  8.51335,  9.077  ,  9.64065, 10.2043 , 10.76795,
       11.3316 , 11.89525, 12.4589 , 13.02255, 13.5862 , 14.14985,
       14.7135 , 15.27715, 15.8408 , 16.40445, 16.9681 , 17.53175,
       18.0954 , 18.65905, 19.2227 , 19.78635, 20.35   , 20.91365,
       21.4773 , 22.04095, 22.6046 , 23.16825, 23.7319 , 24.29555,
       24.8592 , 25.42285, 25.9865 ]), 0.56365)


In [43]:
#Matrics creation

In [44]:
print("vector of zeros \n------------")
print(np.zeros([5]))

vector of zeros 
------------
[0. 0. 0. 0. 0.]


In [45]:
print("vector of zeros \n---------")
print(np.zeros([5,6]))

vector of zeros 
---------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [46]:
#Lets Try with Ones

In [47]:
print("vector of ones \n------------")
print(np.ones([5,6]))

vector of ones 
------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [48]:
#This tecniques only work with zero and ones if you want to print another number then use .below given technique

In [49]:
print("matrix of 5 \n--------")
print(5*np.ones([5,6]))

matrix of 5 
--------
[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [50]:
#Construct diagonal matrix

In [51]:
x=np.arange(30).reshape(5,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [52]:
#Random Number Generation

In [53]:
import numpy as np

In [54]:
np.random.seed(6) # Each seed number will generate similar data
print("Random number genration (from uniform distribution)")
print(np.random.rand(10,6))

Random number genration (from uniform distribution)
[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [55]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml")
print(np.random.randn(10,6))

Number from normal distribution with zero mean and standard deviation 1 i.e standard noraml
[[-0.37550472  0.39636757 -0.47144628  2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539 -0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842 -1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739  1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977 -0.09084699  0.17629034  1.09462041]
 [-2.12647459  0.75144883 -0.54060704  0.79322236  0.17365335 -1.03543429]
 [ 0.87426839 -0.73957208  0.52294535 -0.59187648 -0.47748711  0.11252968]
 [ 1.90474232  0.69415315 -0.01958134  1.66284285  0.03060843 -0.29749921]
 [-0.96813764  0.16706673  0.11660197 -0.68225732 -1.91402115 -0.13990231]
 [ 0.11492459 -0.39500464 -0.95331626 -1.07282736 -0.48444561  1.36293786]]


In [56]:
print("Random integer vector : ",np.random.randint(5,20,10))

Random integer vector :  [ 7 17  6 19 17 19 15 14  7  5]


In [57]:
print("\n Random integer matrix")
print(np.random.randint(1,30000,(6,7)))


 Random integer matrix
[[18780 18307 15355 11222 24641 15656  8972]
 [  599  3367 25489    10 16534 12574 19711]
 [ 7360 29664  7867  7193 14019 13020 13077]
 [18979   100 21484 21802  8255 12325  7663]
 [20160 19121 25216 16774  3611 16808  5847]
 [ 3810  3576 24615  1083 17826 26054  8618]]


In [58]:
#One of the real time example of randint is

In [59]:
def generate_otp():
    otp=np.random.randint(1000,10000,1)
    print("Your Otp is ",otp)
    user_otp=int(input("Enter Your OTP Here"))
    if otp==user_otp:
        print("Log in Sucessfully")
    else:
        print("Your OTP is invalid")

In [60]:
generate_otp()

Your Otp is  [4292]
Enter Your OTP Here4292
Log in Sucessfully
